### ISSUE TITLE
Does the exp results have exceed ConvE?

### ISSUE THREAD

**Issue by shuibinlong** [yuanpeikai/ConvR#1]
Thanks for your good working. But I used the ConvR model in the experiment and found that its effect cannot surpass ConvE. I don’t know what went wrong. Did you find that it got better during the experiment?

**Comment by yuanpeikai** [comment]
thank you ,I have achieved results similar to the paper. If you still have problems, you can configure it according to the recommended configuration in the paper,and I also help you find the problem.

**Comment by shuibinlong** [comment]
Thank you for your reply. After comparing with your code, I reached the expected metrics. XD
